# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d325fbb62789f7a598edda5b0e8b69d7562186f4a9db8e932aa2fadc149cbb5f925f2308971fa8e05e7b96dd8f7dcfc0a85c93e5beaf73a96665f76bacfc2dea

test:
  secret_key_base: 954dc9377e4842fbc51763b7352fa303160acebc4a097929812087d44c4e73c0a6efdf0cd8d5f686ceae2c044a43a748250876fc1ca13c6f1768aa5e57be1d79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
